RECURSE(
    blobsan
    cfg
    query_replay
    query_replay_yt
    simple_queue
    olap_workload
    memcpy_memset_bench
    memory_no_ydb_repro
    tsserver
    tstool
    xxh3_update_bench
    ydbd_slice
)
